### PR TITLE
WSSQL-49 Add Description field, and populate

### PR DESCRIPTION
**Pull request by rpastrana**
Signed-off-by: rpastrana <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@RussWhitehead possibly of interest to you... this will be included in 5.2.0

**Comment by rpastrana** [comment]
@wangkx please review

**Comment by wangkx** [comment]
@rpastrana Other than a minor comment, looks good.

**Comment by rpastrana** [comment]
@wangkx thanks for the review. Please confirm my latest change 
376b400

**Comment by wangkx** [comment]
Looks fine now.

**Pull request merged**
