### PR TITLE
WSSQL-128 Consider aggregate funtion params when verifying sortby grpby

### PR DESCRIPTION
**Pull request by rpastrana**
Signed-off-by: rpastrana <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@wangkx please review.

**Comment by wangkx** [comment]
@rpastrana back to you.

**Comment by rpastrana** [comment]
@wangkx please review latest changes.

**Comment by wangkx** [comment]
@rpastrana looks good now.

**Comment by rpastrana** [comment]
@kunalaswani this will be released in wssql 6.0.0. please add similar test cases to the test suite:
select sum(numericfield) from somefile groupby numericfield;

**Comment by kunalaswani** [comment]
@rpastrana I will start adding cases to the test suite

**Pull request merged**
