### PR TITLE
WSSQL-101 Usability changes based on review

### PR DESCRIPTION
**Pull request by rpastrana**
- Add enumerations for data and field types
- Make file name absolute when setting description
- Improve error messages

Signed-off-by: rpastrana <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@xwang2713

**Comment by rpastrana** [comment]
@wangkx please review

**Comment by wangkx** [comment]
@rpastrana please see my questions.

**Comment by rpastrana** [comment]
All issues addressed. @wangkx  please review.

**Comment by rpastrana** [comment]
reviewed by @wangkx on my screen.

**Pull request merged**
