### PR TITLE
WSSQL-48 Add related index support

### PR DESCRIPTION
**Pull request by rpastrana**
- Added methods for reading DFU file descriptions, and interpreting
  related index annotations, and also setting those annotations

Signed-off-by: rpastrana <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@wangkx  please review.

**Comment by wangkx** [comment]
@rpastrana generally looks good, just a few comments.

**Comment by rpastrana** [comment]
Comments are on the original commit, which was re-based after the code review:
https://github.com/rpastrana/wssql/commit/4111a27b43237282de90240f32af9237d651b0ca

**Comment by rpastrana** [comment]
@wangkx please review changes

**Comment by wangkx** [comment]
@rpastrana please see my question INSIDE bb3351d.

**Comment by rpastrana** [comment]
@wangkx one more review please.

**Comment by wangkx** [comment]
@rpastrana looks good.

**Pull request merged**
