### PR TITLE
WSSQL-96 Add SQL create and load method

### PR DESCRIPTION
**Pull request by rpastrana**
Signed-off-by: rpastrana <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@wangkx please review.

**Comment by wangkx** [comment]
@rpastrana please see my comments.

**Comment by rpastrana** [comment]
@wangkx please review latest changes

**Comment by wangkx** [comment]
@rpastrana looks fine.

**Pull request merged**
